### ISSUE TITLE
extremes_summaries issues

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#100]
- [x] #95 
- [x] station 1 - "Error in purrr::map(.x = summaries, .f = ~overall_extremes_summaries(daily = daily,  : \n  \n\u001b[1mCaused by error in `summarise()`:\u001b[22m\n\u001b[33m!\u001b[39m could not find function \"summarise\"  is returned

**Comment by lilyclements** [comment]
1. See discussed in #96 
2. Thanks - clearly forgot the package name before `summarise`. This was an issue in the rpicsa package, and has now been resolved there. Try updating the package and let me know if this is still an issue.

**Comment by lilyclements** [comment]
This should now be sorted after PR #104
