### ISSUE TITLE
Naming now consistent with R-Instat for crop_success_probabilities

### ISSUE THREAD

**Issue by lilyclements** [IDEMSInternational/epicsawrap#109]
@ChrisMarsh82 just a heads up - I've edited the names of the variables that come out of crop_success_probabilities for consistency with R-Instat:

"planting_dates" is now "plant_day"
"planting_length" is now "plant_length"
"water_requirements" is now "total_rain"

Hope this makes sense.

**Comment by ChrisMarsh82** [comment]
@lilyclements I have changed this for data coming back. It looks like the data being passed in and the meta data are still the old names. Is this correct?

**Comment by lilyclements** [comment]
Yes, just the data that is returned has changed
