### ISSUE TITLE
Use `definition_id` instead of `station_id`

### ISSUE THREAD

**Issue by lilyclements** [IDEMSInternational/epicsawrap#121]
We want to use a `definition_id` instead of a `station_id`. This requires a few changes:

- [x] Amend the station metadata to include a `definition_id` option.
- [x] Amend the definition json files to now call in `definition_id` not `station_id`
- [x] Amend the `epicsawrap` functions (annual_rainfall, etc) where we call `station_id` to automatically call `definition_id` from the station metadata
- [x] Amend the R-Instat function to update the definition file to `definition_id` instead of `station_id`.
- [x] Amend the R-Instat dialog to update the station metadata to include the new definition_id

**Comment by lilyclements** [comment]
@jkmusyoka I am working on this here so that we call definition_id instead of station_id. This will mean some changes required on the R-Instat dialog (which I will outline to Vitalis once I have sorted the R-code).

This will mean that the user will have to define a `definition_id` as well as `station_id`: 

* That `definition_id` will be the name of the outgoing definition data. E.g., it will now be "<definition_id>.<timestamp>.json" instead of "<station_id>.<timestamp>.json"
* The `station_id` will still be used to name any exported station summaries. **Should we have that this is now called `<station_id>.<definition_id>`** for clarity of which definitions it corresponds to? We will still have timestamps so it is currently linked that way. 
* That `definition_id` will update in the metadata, somehow, to state that the user is updating their station and metadata
(I will have to do this by writing a function that calls the metadata from the buckets, updates the metadata to give the new definition_id, and then returns the metadata to the buckets).

This means that all data sets we use for testing and otherwise need to be defined in the metadata.rds file (for now, I have coded in that if they are not in the metadata, to set definition_id as station_id, so you shouldn't get any bugs from these changes).

Can you outline which data sets we are using for testing so I can add them into the metadata? For now, we can set their definition_id to be their station_id I think, until we update the R-Instat function.

**Comment by jkmusyoka** [comment]
@lilyclements 

At the moment, zambia_eastern_4 is the test data from Zambia. It has 5 stations. And now there is a malawi_test folder which has a test dataset for 2 stations. 

There is one more test data from Kenya which I will add this week. I will let you know when it is ready

**Comment by jkmusyoka** [comment]
@lilyclements while you are on this issue, could you also add more "countries" into the epicsa r system namely "ml_test" for malawi test data and "ke_test "for Kenya test data. 

Thanks

**Comment by lilyclements** [comment]
@jkmusyoka thanks for this. I have done this now in [PR 47](https://github.com/IDEMSInternational/epicsadata/pull/47)
