### ISSUE TITLE
General discussion points for the `epicsawrap` functions

### ISSUE THREAD

**Issue by lilyclements** [IDEMSInternational/epicsawrap#15]
I have a few points to work on and discuss. I hope to discuss these over the next week with @volloholic while in Kenya

- [x] For season_start_probabilities I note that `start_dates` is a parameter. I would have expected this parameter to be read in in the json definitions file. What value does this parameter give if it is not read in the json definitions file.
- [x] Same as above, but for the additional parameters in crop_success_probabilities
- [x] I'm currently hardcoding in the variable names from the daily data sets. How do we plan to "read in" the variable names, such as date, rainfall, etc in the `epicsawrap` functions?
- [x] Currently, if we don't have `start_rains` or `end_rains` summaries given in the `annual_summaries` function, but the user wishes to calculate `seasonal_length` or `seasonal_rain`, we pull an error.
- [x] Want to double check and run through this whole "call the daily data from the server each time and don't store it". Feels backwards so just want to double check I understand correctly
- [x] What to do about having DOY at 366 vs 365. Perhaps it's 366 in one place (e.g. SOR), and 365 in another (e.g. EOR). Would this happen? Is this something to discuss? Can this be a "global variable" to read in the definition file to prevent repetitive code for the user, and ensure consistency?

**Comment by lloyddewit** [comment]
@lilyclements PR #10 adds the `end_season` summary to the `annual_rainfall_summaries()` function.
I tried to add a test for this but it failed (see below).
Please could you provide a test for `end_season`?
thanks

![image](https://github.com/IDEMSInternational/epicsawrap/assets/57253949/8c14289a-83c6-4250-8a10-e7c48670fa51)

**Comment by lloyddewit** [comment]
@lilyclements I just read PR #14 .
I understand that only certain summary combinations are valid. So I assume that's the reason why my attempt to use `end_season` above failed.
The error above did not help me as a user. If the user calls the function with an invalid summary combination, then I think the function should raise a meaningful warning.

**Comment by lilyclements** [comment]
@lloyddewit the reason for this is because in the `01122` file for station ID, we do not have defined the `end_season`. I suggest using the `16` file. However! Before you use the `16` file, note that I didn't actually sync the `16` file anyway before you highlighted this issue so it wouldn't have worked then before you pointed this out!

Your second point is a good point - I will add in a more meaningful error to say that the definitions are not given in the json file so cannot be calculated

**Comment by lloyddewit** [comment]
@lilyclements Thank you for the info and updates.
The updated code contains 2 example function calls. I tried both and they both cause problems for the `epicsa-python` package.

`annual_rainfall_summaries(country = "zm", station_id = "16", summaries = c("start_rains", "end_rains", "annual_rain", "end_season"))`

The metadata works correctly.
Some of the data frame columns cause problems for `epicsa-python`:
- year, total_rain, n_rain: these are integers, some of the values are NA, which Python treats as -2147483648. I will try and fix this, preferably by representing as Python null.
- start_rain, end_rain, end_season : these are dates which cause problems for the conversion to Python. Please could you convert to an integer representing DOY?

![image](https://github.com/IDEMSInternational/epicsawrap/assets/57253949/c27ac613-a3f8-42db-89dc-bfd1e5281358)

`annual_rainfall_summaries(country = "zm", station_id = "16", summaries = c("start_rains", "end_rains", "annual_rain", "seasonal_length"))`

This function does not seem to return any metadata. It only seems to return a data frame. The `epicsa-python` is expecting a multi-level list and the conversion fails.
Please could you ensure that the function returns data in the standard format (meta data and data)?

The data frame has the same issues as mentioned above.

Thanks for your help!

**Comment by lloyddewit** [comment]
@lilyclements Thank you for all the prompt changes.
DOY columns seem to be be reals (`start_rain`, `end_rain`). Same for `seasonal_length` and `end_season`. Please could you return integers? 
thanks if possible

![image](https://github.com/IDEMSInternational/epicsawrap/assets/57253949/d827f1d6-7331-4caa-beeb-1ec38766a2ed)

**Comment by lloyddewit** [comment]
@lilyclements Thank you for PR #26.

1. Integers make sense for DOY columns but other columns such as rainfall are reals (unless you think the digits after the decimal point are insignificant and can be removed). Are you sure that **all** numeric columns should be integers?
2. The new version also triggers an error:

![image](https://github.com/IDEMSInternational/epicsawrap/assets/57253949/d9a344de-c123-499e-8d49-f7f3175cc2d0)

3. Finally, there is still an unchecked task in the opening comments above. Before we close this issue, will you check if this still needs some action?

Thanks

T

**Comment by lloyddewit** [comment]
@lilyclements All my automatic tests are now failing because they are expecting real values for columns related to things like temperature and rainfall readings.
It will be a lot of work to check and change all the expected results to convert them to integers. Please could you change this back so that only columns that really should be integers (e.g. years, DOY, counts of days etc) are integers and the other columns stay as reals?
Thanks!

**Comment by lilyclements** [comment]
1. Good question. When do you want to have integers and when do you want to have numerical variables? I assumed the issue was in numerical variables in Python in general, but now I think about it that doesn't make much sense!
Do we want `annual_rain` and `seasonal_rain` to give numerical values for the rainfall as they counts the total. Similarly with `mean_tmin` and `mean_tmax` in the temperature summaries?
I can sort this now.
2. This error occurs because you haven't stated the summaries to give, therefore, it assumes you want to give them all. We haven't defined them all in the `"01122"` file, so it gives an error.
3. Yes this is as a new PR that I will get to

**Comment by lloyddewit** [comment]
> 1. Good question. When do you want to have integers and when do you want to have numerical variables? I assumed the issue was in numerical variables in Python in general, but now I think about it that doesn't make much sense!
>        Do we want `annual_rain` and `seasonal_rain` to give numerical values for the rainfall as they counts the total. Similarly with `mean_tmin` and `mean_tmax` in the temperature summaries?
>        I can sort this now.

sounds good, I agree with your suggestions

>     2. This error occurs because you haven't stated the summaries to give, therefore, it assumes you want to give them all. We haven't defined them all in the `"01122"` file, so it gives an error.

Got it, consider this resolved

**Comment by lloyddewit** [comment]
Other values that should stay as real:
- annual_rainfall_summaries: total_rain
- season_start_probabilities: should all the returned proportions be real?

**Comment by lilyclements** [comment]
Yes, I just noticed the proportions issue! Thanks. I've made the changes in PR #27

**Comment by lilyclements** [comment]
@lloyddewit I have merged it, let me know what you think or if this can be closed

**Comment by lloyddewit** [comment]
> @lloyddewit I have merged it, let me know what you think or if this can be closed

Thank you for the changes. All my comments are resolved.
