### ISSUE TITLE
`crop_success_probabilities()` function fails with error

### ISSUE THREAD

**Issue by lloyddewit** [IDEMSInternational/epicsawrap#23]
@lilyclements This function call used to work. Has there been regression?
thanks

![image](https://github.com/IDEMSInternational/epicsawrap/assets/57253949/13aa20b3-15c5-4d93-b097-a60c2c7a4cee)

**Comment by lilyclements** [comment]
@lloyddewit another simple but silly mistake by me! I removed the package name for various reasons and never added it back in. I've fixed this in

**Comment by lilyclements** [comment]
I'll let you close this if you're happy with the comments / output - I've made some comments in the PR

**Comment by lloyddewit** [comment]
This seems to work now, thank you!
