### ISSUE TITLE
Example function call in `annual_temperature_summaries()` function raises warning

### ISSUE THREAD

**Issue by lloyddewit** [IDEMSInternational/epicsawrap#25]
![image](https://github.com/IDEMSInternational/epicsawrap/assets/57253949/4ddde1b9-71b4-4227-8a72-4fa8cfb6948e)

![image](https://github.com/IDEMSInternational/epicsawrap/assets/57253949/0c2b179b-e693-48dd-922a-cc05fdc09950)

**Comment by lilyclements** [comment]
@lloyddewit is this still an issue for you? It is not happening for me. CAn you try updating your `rpicsa` and `epicsawrap` packages?
