### ISSUE TITLE
API annual_rainfall_summaries not returning end_season

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#34]
In summaries end_season returns internal server error.
This was tested with the following request: 
{
  "country": "zm",
  "station_id": "1",
  "summaries": [
     "end_season"
  ]
}

The following summaries work without any issues ["annual_rain", "start_rains" , "end_rains", "seasonal_length"]

**Comment by ChrisMarsh82** [comment]
@lloyddewit

**Comment by lloyddewit** [comment]
@lilyclements 
This also fails in RStudio:

![image](https://github.com/IDEMSInternational/epicsawrap/assets/57253949/597ab8f4-bdfa-4218-98a3-e5581246d956)

**Comment by lilyclements** [comment]
@ChrisMarsh82 @lloyddewit this isn’t working since the file does not exist for station 1. I have only set up a definitions file with 16. I will set one up for the other stations when we have the definitions, but in the meantime this will only work with ‘station_id = “16”’

**Comment by lilyclements** [comment]
I’ll add in a more useful error to avoid confusion / explain this in the future.

**Comment by lilyclements** [comment]
I've added the overall error message in #36.

@lloyddewit @ChrisMarsh82 question - if a parameter in a definition is missing, do we want an error message that it is missing, or do we want to read in a default instead?

**Comment by lloyddewit** [comment]
> @lloyddewit @ChrisMarsh82 question - if a parameter in a definition is missing, do we want an error message that it is missing, or do we want to read in a default instead?

@lilyclements 
I think an error message would be safer (unless there's a specific fault tolerance requirement that specifies that defaults should be used instead).

**Comment by lilyclements** [comment]
@lloyddewit great thanks. Yes this can be closed I think. I’ll create error messages this afternoon if a parameter is missing in the Json definitions file.
