### ISSUE TITLE
Create function to allow uploading of station data

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#51]
inputs:
Country
station_id
data_file

This should allow users to pass through their station data (eventually directly through climsoft) 
The raw data should not be stored but a summary (or multiple summaries) of the data that then can be used to satisfy all our current functions within the project

This should not delete the existing summary file but date stamp the files added.

Only the latest summary file should be accessed by the functions. The historical summaries will not need to be accessed at the moment as this work is out of scope of this issue.

This will also need a function to allow the uploading of summarised data. This will allow the option for users to create these summaries outside this project and upload them without pushing their raw data to the function.

**Comment by lilyclements** [comment]
This function has been created in `epicsadata` under https://github.com/IDEMSInternational/epicsadata/pull/12

I've added a wrapper to this function in this package in PR #58. If you're happy with this then you can close this PR :)

**Comment by lilyclements** [comment]
> Only the latest summary file should be accessed by the functions

@ChrisMarsh82 just to check:

1. The raw data from the buckets are used in the summary functions.
2. The output from the summary functions can now be uploaded into the buckets (with this new `add_data_to_buckets` wrapper function).

Does this mean I should create a function which accesses the summary data?
At the moment, this function simply adds new data into the bucket. It doesn't distinguish it is summary data.

We can have a few different summary data sets, coming from different functions. Do we want all summary data sets to be upload-able?
* If so, we should have a way that specifies the function that the summaries have come from.
* If not, I assume just the annual summaries (start of rains, end of rains, etc) should be uploadable.

Distinguishing between uploading raw and summary data can be simple. I suggest we have a new folder in the buckets called "summary_data" for the summary data to be stored in. The raw data can still be stored in "raw".
We can just have a parameter which specifies if this is to go as raw or summary data.
We can also have a parameter which adds a prefix specifying which function this has come from (if we have multiple functions creating summary tables to upload).

**Comment by lilyclements** [comment]
I think once you respond to the point above I'll be clearer about this "summary" data.

> Only the latest summary file should be accessed by the functions

@ChrisMarsh82 just to check:
* The daily data is used in our summary functions to give a summary output.
* Any data frame can now be uploaded into the buckets (with this new `add_data_to_buckets` wrapper function).

Do we want the **summary data that comes out of these functions** to be upload-able into the buckets? If we do, then I have a few questions:

1. I suggest we distinguish between the summary data and daily data by having different file directories. To do this, I'll add a parameter which specifies if the uploaded data is raw or summary data. This simply changes the file directory we upload to.

* "summary_data" has the summary data 
* "data" contains the daily data

2. We can have a few different summary data sets, coming from different functions. Do we want all summary data sets to be upload-able?
If so, I can add a parameter which adds a prefix specifying which function this has come from (if we have multiple functions creating summary tables to upload).

3.  Does this mean I should create a function which accesses the summary data?

**Comment by lilyclements** [comment]
> The raw data should not be stored but a summary (or multiple summaries) of the data that then can be used to satisfy all our current functions within the project

@ChrisMarsh82 Perhaps we have different definitions of "raw data". What do you mean by "raw data"? 
What do you mean by "summary data"?

* My definition of "raw data" is the daily data. 
* My definition of "summary data" is the data that comes from our written summary functions.

The daily (or what I call "raw") data from the buckets are used in the summary functions because we look at the daily data to get the annual/monthly data.
How can we calculate summary data with data which is not the daily data?

**Comment by lilyclements** [comment]
fixed by https://github.com/IDEMSInternational/epicsawrap/pull/88
