### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#76]
- [x]  annual rainfall summaries. _last_updated - change name not to start with _
- [x]  _last_updated comes back as a date and not a float. Can other dates do this?
- [x]  temperature summaries - max_tmax works but does not bring back metadata
- [x] temperature summaries - min_tmin, min_tmax and max_tmin do not work
- [x] extremes_summaries - do not get metadata for tmin and tmax
- [x] Metadata - Why are they lists? - Think this is a Python issue
- [x]  station - can definitions come back in the same format as metadata?
- [ ] Confirm response models
- [x] Confirm inputs

Test Data
- [x] crop_success_probabilities - need good example data
- [x] season_start_probabilities

**Comment by lilyclements** [comment]
* `min_tmax` and `max_tmin` are added in for test_1 and 1. 
* dates should come back as a float now given #78 
* extremes_summaries has been rejigged. All extremes are now accessible through `extremes_summaries`

Note:
* year is now coming back as a year after changes relating to shifted start year and handling giving the output even if there is a 0 in that year
e.g. if we have no start of rains one year, if year is a factor, we get that data output with an `NA` if `year` is a factor.
If `year` is not a factor, we would not get that line in the data output


I will get to the others tomorrow

**Comment by lilyclements** [comment]
PR #87 fixes the request:

> station - can definitions come back in the same format as metadata?

This PR adds functionality to ensure definitions can come back in the same format at the metadata (list format).

This can be achieved by running `format = "list"` in the function, e.g.,

```
station_metadata("zm", station_id = c(1, 28), include_definitions = TRUE, format = "list")
```

**Comment by lilyclements** [comment]
@ChrisMarsh82 how should we edit the test data for  crop_success_probabilities and season_start_probabilities?

**Comment by ChrisMarsh82** [comment]
Closing issue as response models will be confirmed seperatley to this
