### ISSUE TITLE
Test_1 - metadata does not come back in the right format. "definition from summary" is all that is returned.

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#95]
This is the case for all functions

**Comment by lilyclements** [comment]
We need to discuss here how we want to do this. The summary is one file and the definitions is another. What if the user updates the summary and not the definitions file?

My idea at the moment is that the time stamps will be useful to match the correct definitions. Presumably we call the most recent summary, and the definitions that corresponds to that?

What if there is no corresponding definition?

**Comment by lilyclements** [comment]
I have fixed for "annual_rainfall_summaries" in PR #103. I will fix in the others tomorrow

**Comment by lilyclements** [comment]
This should now be sorted after PR https://github.com/IDEMSInternational/epicsawrap/pull/104
