### ISSUE TITLE
crop_success_probabilities issues

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#97]
- [x] station 1 - using   "water_requirements": [300, 500, 700],  "planting_length": [120, 180],  "planting_dates": [92,122,153] - prob_success is always 0 
- [x] #95

**Comment by lilyclements** [comment]
@ChrisMarsh82 what is the problem with point 1? If I change the values, it does work, so I assume that the issue is with the definitions from ZMD, not with the code?

E.g., try
```
crop_success_probabilities("zm", "1", override = FALSE,
                           water_requirements = c(100, 200, 300),
                           planting_dates = c(25, 50, 75),
                           planting_length = c(20))
```

2. Discussed in issue #95
