### ISSUE TITLE
monthly_temperature_summaries issues

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#98]
- [x]  errors when "min_tmin", "min_tmax", "max_tmin", "max_tmax" is entered
- [x] #95

**Comment by lilyclements** [comment]
@ChrisMarsh82 see comments on #96

**Comment by lilyclements** [comment]
This should now be sorted after PR https://github.com/IDEMSInternational/epicsawrap/pull/104

**Comment by ChrisMarsh82** [comment]
I still have the issue "errors when "min_tmin", "min_tmax", "max_tmin", "max_tmax" is entered"
I get this error back
"msg": "unexpected value; permitted: 'mean_tmin', 'mean_tmax'",
      "type": "value_error.const",
      "ctx": {
        "given": "min_tmin",
        "permitted": [
          "mean_tmin",
          "mean_tmax"
        ]

**Comment by lilyclements** [comment]
Can you confirm that the definitions contain these summaries?
Can you confirm that the override is TRUE

**Comment by ChrisMarsh82** [comment]
This was an issue on the python side. I have been able to run it fine through r. Apologies. Will fix my side.
